# Generated by Django 2.1.7 on 2019-04-13 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_dir', models.CharField(max_length=512, verbose_name='文件主目录')),
                ('file_path', models.CharField(max_length=512, verbose_name='文件路径')),
                ('file_name', models.CharField(max_length=128, verbose_name='文件名')),
                ('update_time', models.DateTimeField(verbose_name='上传时间')),
                ('file_type', models.CharField(max_length=32, verbose_name='文件类型')),
                ('file_size', models.CharField(max_length=16, verbose_name='文件大小')),
                ('full_path', models.CharField(max_length=512, verbose_name='文件总路径')),
                ('user', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
